//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 19/09/2009 17:04:53
namespace OpenTibiaXna.OTServer.Entities
{
    
    /// <summary>
    /// There are no comments for SQLiteEntities in the schema.
    /// </summary>
    public partial class SQLiteEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new SQLiteEntities object using the connection string found in the 'SQLiteEntities' section of the application configuration file.
        /// </summary>
        public SQLiteEntities() : 
                base("name=SQLiteEntities", "SQLiteEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SQLiteEntities object.
        /// </summary>
        public SQLiteEntities(string connectionString) : 
                base(connectionString, "SQLiteEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SQLiteEntities object.
        /// </summary>
        public SQLiteEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SQLiteEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
    }
}
