//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MSSQLModel", "FK_Player_AccountId_Account_AccountId", "Account", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OpenTibiaXna.OTServer.Entities.Account), "Player", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OpenTibiaXna.OTServer.Entities.Player))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MSSQLModel", "FK_Player_GameWorldId_GameWorld_GameWorldId", "GameWorld", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OpenTibiaXna.OTServer.Entities.GameWorld), "Player", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OpenTibiaXna.OTServer.Entities.Player))]

// Original file name:
// Generation date: 19/09/2009 19:44:27
namespace OpenTibiaXna.OTServer.Entities
{
    
    /// <summary>
    /// There are no comments for MSSQLEntities in the schema.
    /// </summary>
    public partial class MSSQLEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MSSQLEntities object using the connection string found in the 'MSSQLEntities' section of the application configuration file.
        /// </summary>
        public MSSQLEntities() : 
                base("name=MSSQLEntities", "MSSQLEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MSSQLEntities object.
        /// </summary>
        public MSSQLEntities(string connectionString) : 
                base(connectionString, "MSSQLEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MSSQLEntities object.
        /// </summary>
        public MSSQLEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MSSQLEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Account in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Account> Account
        {
            get
            {
                if ((this._Account == null))
                {
                    this._Account = base.CreateQuery<Account>("[Account]");
                }
                return this._Account;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Account> _Account;
        /// <summary>
        /// There are no comments for GameWorld in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<GameWorld> GameWorld
        {
            get
            {
                if ((this._GameWorld == null))
                {
                    this._GameWorld = base.CreateQuery<GameWorld>("[GameWorld]");
                }
                return this._GameWorld;
            }
        }
        private global::System.Data.Objects.ObjectQuery<GameWorld> _GameWorld;
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Item> Item
        {
            get
            {
                if ((this._Item == null))
                {
                    this._Item = base.CreateQuery<Item>("[Item]");
                }
                return this._Item;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Item> _Item;
        /// <summary>
        /// There are no comments for MapItem in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<MapItem> MapItem
        {
            get
            {
                if ((this._MapItem == null))
                {
                    this._MapItem = base.CreateQuery<MapItem>("[MapItem]");
                }
                return this._MapItem;
            }
        }
        private global::System.Data.Objects.ObjectQuery<MapItem> _MapItem;
        /// <summary>
        /// There are no comments for MapTile in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<MapTile> MapTile
        {
            get
            {
                if ((this._MapTile == null))
                {
                    this._MapTile = base.CreateQuery<MapTile>("[MapTile]");
                }
                return this._MapTile;
            }
        }
        private global::System.Data.Objects.ObjectQuery<MapTile> _MapTile;
        /// <summary>
        /// There are no comments for Player in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Player> Player
        {
            get
            {
                if ((this._Player == null))
                {
                    this._Player = base.CreateQuery<Player>("[Player]");
                }
                return this._Player;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Player> _Player;
        /// <summary>
        /// There are no comments for Account in the schema.
        /// </summary>
        public void AddToAccount(Account account)
        {
            base.AddObject("Account", account);
        }
        /// <summary>
        /// There are no comments for GameWorld in the schema.
        /// </summary>
        public void AddToGameWorld(GameWorld gameWorld)
        {
            base.AddObject("GameWorld", gameWorld);
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        public void AddToItem(Item item)
        {
            base.AddObject("Item", item);
        }
        /// <summary>
        /// There are no comments for MapItem in the schema.
        /// </summary>
        public void AddToMapItem(MapItem mapItem)
        {
            base.AddObject("MapItem", mapItem);
        }
        /// <summary>
        /// There are no comments for MapTile in the schema.
        /// </summary>
        public void AddToMapTile(MapTile mapTile)
        {
            base.AddObject("MapTile", mapTile);
        }
        /// <summary>
        /// There are no comments for Player in the schema.
        /// </summary>
        public void AddToPlayer(Player player)
        {
            base.AddObject("Player", player);
        }
    }
    /// <summary>
    /// There are no comments for MSSQLModel.Account in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AccountId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MSSQLModel", Name="Account")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Account : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Account object.
        /// </summary>
        /// <param name="accountId">Initial value of AccountId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="password">Initial value of Password.</param>
        public static Account CreateAccount(int accountId, string name, string password)
        {
            Account account = new Account();
            account.AccountId = accountId;
            account.Name = name;
            account.Password = password;
            return account;
        }
        /// <summary>
        /// There are no comments for Property AccountId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId
        {
            get
            {
                return this._AccountId;
            }
            set
            {
                this.OnAccountIdChanging(value);
                this.ReportPropertyChanging("AccountId");
                this._AccountId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AccountId");
                this.OnAccountIdChanged();
            }
        }
        private int _AccountId;
        partial void OnAccountIdChanging(int value);
        partial void OnAccountIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Player in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MSSQLModel", "FK_Player_AccountId_Account_AccountId", "Player")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Player> Player
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Player>("MSSQLModel.FK_Player_AccountId_Account_AccountId", "Player");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Player>("MSSQLModel.FK_Player_AccountId_Account_AccountId", "Player", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MSSQLModel.GameWorld in the schema.
    /// </summary>
    /// <KeyProperties>
    /// GameWorldId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MSSQLModel", Name="GameWorld")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class GameWorld : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new GameWorld object.
        /// </summary>
        /// <param name="gameWorldId">Initial value of GameWorldId.</param>
        /// <param name="gameWorldName">Initial value of GameWorldName.</param>
        /// <param name="gameWorldIp">Initial value of GameWorldIp.</param>
        /// <param name="gameWorldPort">Initial value of GameWorldPort.</param>
        public static GameWorld CreateGameWorld(int gameWorldId, string gameWorldName, byte[] gameWorldIp, short gameWorldPort)
        {
            GameWorld gameWorld = new GameWorld();
            gameWorld.GameWorldId = gameWorldId;
            gameWorld.GameWorldName = gameWorldName;
            gameWorld.GameWorldIp = gameWorldIp;
            gameWorld.GameWorldPort = gameWorldPort;
            return gameWorld;
        }
        /// <summary>
        /// There are no comments for Property GameWorldId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int GameWorldId
        {
            get
            {
                return this._GameWorldId;
            }
            set
            {
                this.OnGameWorldIdChanging(value);
                this.ReportPropertyChanging("GameWorldId");
                this._GameWorldId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GameWorldId");
                this.OnGameWorldIdChanged();
            }
        }
        private int _GameWorldId;
        partial void OnGameWorldIdChanging(int value);
        partial void OnGameWorldIdChanged();
        /// <summary>
        /// There are no comments for Property GameWorldName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string GameWorldName
        {
            get
            {
                return this._GameWorldName;
            }
            set
            {
                this.OnGameWorldNameChanging(value);
                this.ReportPropertyChanging("GameWorldName");
                this._GameWorldName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("GameWorldName");
                this.OnGameWorldNameChanged();
            }
        }
        private string _GameWorldName;
        partial void OnGameWorldNameChanging(string value);
        partial void OnGameWorldNameChanged();
        /// <summary>
        /// There are no comments for Property GameWorldIp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] GameWorldIp
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._GameWorldIp);
            }
            set
            {
                this.OnGameWorldIpChanging(value);
                this.ReportPropertyChanging("GameWorldIp");
                this._GameWorldIp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("GameWorldIp");
                this.OnGameWorldIpChanged();
            }
        }
        private byte[] _GameWorldIp;
        partial void OnGameWorldIpChanging(byte[] value);
        partial void OnGameWorldIpChanged();
        /// <summary>
        /// There are no comments for Property GameWorldPort in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short GameWorldPort
        {
            get
            {
                return this._GameWorldPort;
            }
            set
            {
                this.OnGameWorldPortChanging(value);
                this.ReportPropertyChanging("GameWorldPort");
                this._GameWorldPort = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GameWorldPort");
                this.OnGameWorldPortChanged();
            }
        }
        private short _GameWorldPort;
        partial void OnGameWorldPortChanging(short value);
        partial void OnGameWorldPortChanged();
        /// <summary>
        /// There are no comments for Player in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MSSQLModel", "FK_Player_GameWorldId_GameWorld_GameWorldId", "Player")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Player> Player
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Player>("MSSQLModel.FK_Player_GameWorldId_GameWorld_GameWorldId", "Player");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Player>("MSSQLModel.FK_Player_GameWorldId_GameWorld_GameWorldId", "Player", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MSSQLModel.Item in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ItemId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MSSQLModel", Name="Item")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Item : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="itemId">Initial value of ItemId.</param>
        public static Item CreateItem(int itemId)
        {
            Item item = new Item();
            item.ItemId = itemId;
            return item;
        }
        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId
        {
            get
            {
                return this._ItemId;
            }
            set
            {
                this.OnItemIdChanging(value);
                this.ReportPropertyChanging("ItemId");
                this._ItemId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ItemId");
                this.OnItemIdChanged();
            }
        }
        private int _ItemId;
        partial void OnItemIdChanging(int value);
        partial void OnItemIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for MSSQLModel.MapItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// X
    /// Y
    /// Z
    /// StackPosition
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MSSQLModel", Name="MapItem")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MapItem : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new MapItem object.
        /// </summary>
        /// <param name="x">Initial value of X.</param>
        /// <param name="y">Initial value of Y.</param>
        /// <param name="z">Initial value of Z.</param>
        /// <param name="stackPosition">Initial value of StackPosition.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="extra">Initial value of Extra.</param>
        public static MapItem CreateMapItem(short x, short y, short z, short stackPosition, short id, short extra)
        {
            MapItem mapItem = new MapItem();
            mapItem.X = x;
            mapItem.Y = y;
            mapItem.Z = z;
            mapItem.StackPosition = stackPosition;
            mapItem.Id = id;
            mapItem.Extra = extra;
            return mapItem;
        }
        /// <summary>
        /// There are no comments for Property X in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short X
        {
            get
            {
                return this._X;
            }
            set
            {
                this.OnXChanging(value);
                this.ReportPropertyChanging("X");
                this._X = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("X");
                this.OnXChanged();
            }
        }
        private short _X;
        partial void OnXChanging(short value);
        partial void OnXChanged();
        /// <summary>
        /// There are no comments for Property Y in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Y
        {
            get
            {
                return this._Y;
            }
            set
            {
                this.OnYChanging(value);
                this.ReportPropertyChanging("Y");
                this._Y = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Y");
                this.OnYChanged();
            }
        }
        private short _Y;
        partial void OnYChanging(short value);
        partial void OnYChanged();
        /// <summary>
        /// There are no comments for Property Z in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Z
        {
            get
            {
                return this._Z;
            }
            set
            {
                this.OnZChanging(value);
                this.ReportPropertyChanging("Z");
                this._Z = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Z");
                this.OnZChanged();
            }
        }
        private short _Z;
        partial void OnZChanging(short value);
        partial void OnZChanged();
        /// <summary>
        /// There are no comments for Property StackPosition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short StackPosition
        {
            get
            {
                return this._StackPosition;
            }
            set
            {
                this.OnStackPositionChanging(value);
                this.ReportPropertyChanging("StackPosition");
                this._StackPosition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StackPosition");
                this.OnStackPositionChanged();
            }
        }
        private short _StackPosition;
        partial void OnStackPositionChanging(short value);
        partial void OnStackPositionChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private short _Id;
        partial void OnIdChanging(short value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Extra in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Extra
        {
            get
            {
                return this._Extra;
            }
            set
            {
                this.OnExtraChanging(value);
                this.ReportPropertyChanging("Extra");
                this._Extra = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Extra");
                this.OnExtraChanged();
            }
        }
        private short _Extra;
        partial void OnExtraChanging(short value);
        partial void OnExtraChanged();
    }
    /// <summary>
    /// There are no comments for MSSQLModel.MapTile in the schema.
    /// </summary>
    /// <KeyProperties>
    /// X
    /// Y
    /// Z
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MSSQLModel", Name="MapTile")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MapTile : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new MapTile object.
        /// </summary>
        /// <param name="x">Initial value of X.</param>
        /// <param name="y">Initial value of Y.</param>
        /// <param name="z">Initial value of Z.</param>
        /// <param name="groundId">Initial value of GroundId.</param>
        public static MapTile CreateMapTile(short x, short y, short z, short groundId)
        {
            MapTile mapTile = new MapTile();
            mapTile.X = x;
            mapTile.Y = y;
            mapTile.Z = z;
            mapTile.GroundId = groundId;
            return mapTile;
        }
        /// <summary>
        /// There are no comments for Property X in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short X
        {
            get
            {
                return this._X;
            }
            set
            {
                this.OnXChanging(value);
                this.ReportPropertyChanging("X");
                this._X = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("X");
                this.OnXChanged();
            }
        }
        private short _X;
        partial void OnXChanging(short value);
        partial void OnXChanged();
        /// <summary>
        /// There are no comments for Property Y in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Y
        {
            get
            {
                return this._Y;
            }
            set
            {
                this.OnYChanging(value);
                this.ReportPropertyChanging("Y");
                this._Y = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Y");
                this.OnYChanged();
            }
        }
        private short _Y;
        partial void OnYChanging(short value);
        partial void OnYChanged();
        /// <summary>
        /// There are no comments for Property Z in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Z
        {
            get
            {
                return this._Z;
            }
            set
            {
                this.OnZChanging(value);
                this.ReportPropertyChanging("Z");
                this._Z = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Z");
                this.OnZChanged();
            }
        }
        private short _Z;
        partial void OnZChanging(short value);
        partial void OnZChanged();
        /// <summary>
        /// There are no comments for Property GroundId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short GroundId
        {
            get
            {
                return this._GroundId;
            }
            set
            {
                this.OnGroundIdChanging(value);
                this.ReportPropertyChanging("GroundId");
                this._GroundId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GroundId");
                this.OnGroundIdChanged();
            }
        }
        private short _GroundId;
        partial void OnGroundIdChanging(short value);
        partial void OnGroundIdChanged();
    }
    /// <summary>
    /// There are no comments for MSSQLModel.Player in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PlayerId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MSSQLModel", Name="Player")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Player : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Player object.
        /// </summary>
        /// <param name="playerId">Initial value of PlayerId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="gender">Initial value of Gender.</param>
        /// <param name="vocation">Initial value of Vocation.</param>
        /// <param name="level">Initial value of Level.</param>
        /// <param name="magicLevel">Initial value of MagicLevel.</param>
        /// <param name="experience">Initial value of Experience.</param>
        /// <param name="maxHealth">Initial value of MaxHealth.</param>
        /// <param name="maxMana">Initial value of MaxMana.</param>
        /// <param name="capacity">Initial value of Capacity.</param>
        /// <param name="outfitLookType">Initial value of OutfitLookType.</param>
        /// <param name="outfitHead">Initial value of OutfitHead.</param>
        /// <param name="outfitBody">Initial value of OutfitBody.</param>
        /// <param name="outfitLegs">Initial value of OutfitLegs.</param>
        /// <param name="outfitFeet">Initial value of OutfitFeet.</param>
        /// <param name="outfitAddons">Initial value of OutfitAddons.</param>
        public static Player CreatePlayer(
                    int playerId, 
                    string name, 
                    short gender, 
                    int vocation, 
                    int level, 
                    short magicLevel, 
                    long experience, 
                    int maxHealth, 
                    int maxMana, 
                    int capacity, 
                    short outfitLookType, 
                    short outfitHead, 
                    short outfitBody, 
                    short outfitLegs, 
                    short outfitFeet, 
                    short outfitAddons)
        {
            Player player = new Player();
            player.PlayerId = playerId;
            player.Name = name;
            player.Gender = gender;
            player.Vocation = vocation;
            player.Level = level;
            player.MagicLevel = magicLevel;
            player.Experience = experience;
            player.MaxHealth = maxHealth;
            player.MaxMana = maxMana;
            player.Capacity = capacity;
            player.OutfitLookType = outfitLookType;
            player.OutfitHead = outfitHead;
            player.OutfitBody = outfitBody;
            player.OutfitLegs = outfitLegs;
            player.OutfitFeet = outfitFeet;
            player.OutfitAddons = outfitAddons;
            return player;
        }
        /// <summary>
        /// There are no comments for Property PlayerId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId
        {
            get
            {
                return this._PlayerId;
            }
            set
            {
                this.OnPlayerIdChanging(value);
                this.ReportPropertyChanging("PlayerId");
                this._PlayerId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PlayerId");
                this.OnPlayerIdChanged();
            }
        }
        private int _PlayerId;
        partial void OnPlayerIdChanging(int value);
        partial void OnPlayerIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Gender in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this.ReportPropertyChanging("Gender");
                this._Gender = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Gender");
                this.OnGenderChanged();
            }
        }
        private short _Gender;
        partial void OnGenderChanging(short value);
        partial void OnGenderChanged();
        /// <summary>
        /// There are no comments for Property Vocation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Vocation
        {
            get
            {
                return this._Vocation;
            }
            set
            {
                this.OnVocationChanging(value);
                this.ReportPropertyChanging("Vocation");
                this._Vocation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Vocation");
                this.OnVocationChanged();
            }
        }
        private int _Vocation;
        partial void OnVocationChanging(int value);
        partial void OnVocationChanged();
        /// <summary>
        /// There are no comments for Property Level in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this.OnLevelChanging(value);
                this.ReportPropertyChanging("Level");
                this._Level = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Level");
                this.OnLevelChanged();
            }
        }
        private int _Level;
        partial void OnLevelChanging(int value);
        partial void OnLevelChanged();
        /// <summary>
        /// There are no comments for Property MagicLevel in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short MagicLevel
        {
            get
            {
                return this._MagicLevel;
            }
            set
            {
                this.OnMagicLevelChanging(value);
                this.ReportPropertyChanging("MagicLevel");
                this._MagicLevel = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MagicLevel");
                this.OnMagicLevelChanged();
            }
        }
        private short _MagicLevel;
        partial void OnMagicLevelChanging(short value);
        partial void OnMagicLevelChanged();
        /// <summary>
        /// There are no comments for Property Experience in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Experience
        {
            get
            {
                return this._Experience;
            }
            set
            {
                this.OnExperienceChanging(value);
                this.ReportPropertyChanging("Experience");
                this._Experience = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Experience");
                this.OnExperienceChanged();
            }
        }
        private long _Experience;
        partial void OnExperienceChanging(long value);
        partial void OnExperienceChanged();
        /// <summary>
        /// There are no comments for Property MaxHealth in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxHealth
        {
            get
            {
                return this._MaxHealth;
            }
            set
            {
                this.OnMaxHealthChanging(value);
                this.ReportPropertyChanging("MaxHealth");
                this._MaxHealth = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MaxHealth");
                this.OnMaxHealthChanged();
            }
        }
        private int _MaxHealth;
        partial void OnMaxHealthChanging(int value);
        partial void OnMaxHealthChanged();
        /// <summary>
        /// There are no comments for Property MaxMana in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxMana
        {
            get
            {
                return this._MaxMana;
            }
            set
            {
                this.OnMaxManaChanging(value);
                this.ReportPropertyChanging("MaxMana");
                this._MaxMana = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MaxMana");
                this.OnMaxManaChanged();
            }
        }
        private int _MaxMana;
        partial void OnMaxManaChanging(int value);
        partial void OnMaxManaChanged();
        /// <summary>
        /// There are no comments for Property Capacity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacity
        {
            get
            {
                return this._Capacity;
            }
            set
            {
                this.OnCapacityChanging(value);
                this.ReportPropertyChanging("Capacity");
                this._Capacity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Capacity");
                this.OnCapacityChanged();
            }
        }
        private int _Capacity;
        partial void OnCapacityChanging(int value);
        partial void OnCapacityChanged();
        /// <summary>
        /// There are no comments for Property OutfitLookType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short OutfitLookType
        {
            get
            {
                return this._OutfitLookType;
            }
            set
            {
                this.OnOutfitLookTypeChanging(value);
                this.ReportPropertyChanging("OutfitLookType");
                this._OutfitLookType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OutfitLookType");
                this.OnOutfitLookTypeChanged();
            }
        }
        private short _OutfitLookType;
        partial void OnOutfitLookTypeChanging(short value);
        partial void OnOutfitLookTypeChanged();
        /// <summary>
        /// There are no comments for Property OutfitHead in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short OutfitHead
        {
            get
            {
                return this._OutfitHead;
            }
            set
            {
                this.OnOutfitHeadChanging(value);
                this.ReportPropertyChanging("OutfitHead");
                this._OutfitHead = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OutfitHead");
                this.OnOutfitHeadChanged();
            }
        }
        private short _OutfitHead;
        partial void OnOutfitHeadChanging(short value);
        partial void OnOutfitHeadChanged();
        /// <summary>
        /// There are no comments for Property OutfitBody in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short OutfitBody
        {
            get
            {
                return this._OutfitBody;
            }
            set
            {
                this.OnOutfitBodyChanging(value);
                this.ReportPropertyChanging("OutfitBody");
                this._OutfitBody = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OutfitBody");
                this.OnOutfitBodyChanged();
            }
        }
        private short _OutfitBody;
        partial void OnOutfitBodyChanging(short value);
        partial void OnOutfitBodyChanged();
        /// <summary>
        /// There are no comments for Property OutfitLegs in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short OutfitLegs
        {
            get
            {
                return this._OutfitLegs;
            }
            set
            {
                this.OnOutfitLegsChanging(value);
                this.ReportPropertyChanging("OutfitLegs");
                this._OutfitLegs = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OutfitLegs");
                this.OnOutfitLegsChanged();
            }
        }
        private short _OutfitLegs;
        partial void OnOutfitLegsChanging(short value);
        partial void OnOutfitLegsChanged();
        /// <summary>
        /// There are no comments for Property OutfitFeet in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short OutfitFeet
        {
            get
            {
                return this._OutfitFeet;
            }
            set
            {
                this.OnOutfitFeetChanging(value);
                this.ReportPropertyChanging("OutfitFeet");
                this._OutfitFeet = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OutfitFeet");
                this.OnOutfitFeetChanged();
            }
        }
        private short _OutfitFeet;
        partial void OnOutfitFeetChanging(short value);
        partial void OnOutfitFeetChanged();
        /// <summary>
        /// There are no comments for Property OutfitAddons in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short OutfitAddons
        {
            get
            {
                return this._OutfitAddons;
            }
            set
            {
                this.OnOutfitAddonsChanging(value);
                this.ReportPropertyChanging("OutfitAddons");
                this._OutfitAddons = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OutfitAddons");
                this.OnOutfitAddonsChanged();
            }
        }
        private short _OutfitAddons;
        partial void OnOutfitAddonsChanging(short value);
        partial void OnOutfitAddonsChanged();
        /// <summary>
        /// There are no comments for Property LocationX in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> LocationX
        {
            get
            {
                return this._LocationX;
            }
            set
            {
                this.OnLocationXChanging(value);
                this.ReportPropertyChanging("LocationX");
                this._LocationX = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LocationX");
                this.OnLocationXChanged();
            }
        }
        private global::System.Nullable<short> _LocationX;
        partial void OnLocationXChanging(global::System.Nullable<short> value);
        partial void OnLocationXChanged();
        /// <summary>
        /// There are no comments for Property LocationY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> LocationY
        {
            get
            {
                return this._LocationY;
            }
            set
            {
                this.OnLocationYChanging(value);
                this.ReportPropertyChanging("LocationY");
                this._LocationY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LocationY");
                this.OnLocationYChanged();
            }
        }
        private global::System.Nullable<short> _LocationY;
        partial void OnLocationYChanging(global::System.Nullable<short> value);
        partial void OnLocationYChanged();
        /// <summary>
        /// There are no comments for Property LocationZ in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> LocationZ
        {
            get
            {
                return this._LocationZ;
            }
            set
            {
                this.OnLocationZChanging(value);
                this.ReportPropertyChanging("LocationZ");
                this._LocationZ = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LocationZ");
                this.OnLocationZChanged();
            }
        }
        private global::System.Nullable<short> _LocationZ;
        partial void OnLocationZChanging(global::System.Nullable<short> value);
        partial void OnLocationZChanged();
        /// <summary>
        /// There are no comments for Property Direction in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> Direction
        {
            get
            {
                return this._Direction;
            }
            set
            {
                this.OnDirectionChanging(value);
                this.ReportPropertyChanging("Direction");
                this._Direction = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Direction");
                this.OnDirectionChanged();
            }
        }
        private global::System.Nullable<short> _Direction;
        partial void OnDirectionChanging(global::System.Nullable<short> value);
        partial void OnDirectionChanged();
        /// <summary>
        /// There are no comments for Account in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MSSQLModel", "FK_Player_AccountId_Account_AccountId", "Account")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Account Account
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("MSSQLModel.FK_Player_AccountId_Account_AccountId", "Account").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("MSSQLModel.FK_Player_AccountId_Account_AccountId", "Account").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Account in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Account> AccountReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("MSSQLModel.FK_Player_AccountId_Account_AccountId", "Account");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Account>("MSSQLModel.FK_Player_AccountId_Account_AccountId", "Account", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for GameWorld in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MSSQLModel", "FK_Player_GameWorldId_GameWorld_GameWorldId", "GameWorld")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public GameWorld GameWorld
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<GameWorld>("MSSQLModel.FK_Player_GameWorldId_GameWorld_GameWorldId", "GameWorld").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<GameWorld>("MSSQLModel.FK_Player_GameWorldId_GameWorld_GameWorldId", "GameWorld").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for GameWorld in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<GameWorld> GameWorldReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<GameWorld>("MSSQLModel.FK_Player_GameWorldId_GameWorld_GameWorldId", "GameWorld");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<GameWorld>("MSSQLModel.FK_Player_GameWorldId_GameWorld_GameWorldId", "GameWorld", value);
                }
            }
        }
    }
}
